-- Broken task SQL mirrored for the cloud agent to PR against.
-- Bug: AMOUNT was renamed to ORDER_TOTAL on ADE_DEMO.OPS.ORDERS.
INSERT INTO ADE_DEMO.OPS.ORDERS_DAILY
SELECT ORDER_ID, ORDER_TOTAL, ORDER_TS
FROM ADE_DEMO.OPS.ORDERS
WHERE ORDER_TS >= DATEADD('day', -1, CURRENT_TIMESTAMP());
